HAL: PIN Direction API
PIN Direction API
PIN manipulation module
Pin direction manipulation.
Functions
static void pin_output_pushpull (const uint32_t pin)
Set pin to GPIO Output mode, source and sink.
static void pin_output_opendrain (const uint32_t pin)
Set pin to GPIO Output mode, sink only.
static void pin_af_pushpull (const uint32_t pin)
Set pin to AuxFn Output mode, source and sink.
static void pin_af_opendrain (const uint32_t pin)
Set pin to AuxFn Output mode, sink only.
static void pin_input (const uint32_t pin)
Set pin to Input mode.
static void pin_analog (const uint32_t pin)
Set pin to Analog mode.
Detailed Description
Pin direction manipulation.
Function Documentation
static void pin_af_opendrain (const uint32_t pin) static
Set pin to AuxFn Output mode, sink only.
Parameters
[in] pin pin name (pin_name_base)
Definition at line 128 of file pin_v0.h.
References _pin_pin(), _pin_pinno(), _pin_port(), and _pin_setmode().
static void pin_af_pushpull (const uint32_t pin) static
Set pin to AuxFn Output mode, source and sink.
Parameters
[in] pin pin name (pin_name_base)
Definition at line 123 of file pin_v0.h.
References _pin_pin(), _pin_pinno(), _pin_port(), and _pin_setmode().
static void pin_analog (const uint32_t pin) static
Set pin to Analog mode.
This mode disconnects all digital electronics from the pin, allowing to float everywhere between 0 and VDD of the chip.
Parameters
[in] pin pin name (pin_name_base)
Definition at line 138 of file pin_v0.h.
References _pin_pinno(), _pin_port(), and _pin_setmode().
static void pin_input (const uint32_t pin) static
Set pin to Input mode.
Note
In this mode, the pin_speed_* functions are useless
Parameters
[in] pin pin name (pin_name_base)
Definition at line 133 of file pin_v0.h.
References _pin_pinno(), _pin_port(), and _pin_setmode().
static void pin_output_opendrain (const uint32_t pin) static
Set pin to GPIO Output mode, sink only.
Parameters
[in] pin pin name (pin_name_base)
Definition at line 118 of file pin_v0.h.
References _pin_pin(), _pin_pinno(), _pin_port(), and _pin_setmode().
static void pin_output_pushpull (const uint32_t pin) static
Set pin to GPIO Output mode, source and sink.
Parameters
[in] pin pin name (pin_name_base)
Definition at line 82 of file pin_v1.h.
References _pin_pin(), _pin_pinno(), and _pin_port().