HAL: PIN Speed API
PIN Speed API
PIN manipulation module
Pin speed manipulation.
Functions
static void pin_speed_low (const uint32_t pin)
Set pin speed to slowest mode.
static void pin_speed_medium (const uint32_t pin)
Set pin speed to medium speed mode.
static void pin_speed_fast (const uint32_t pin)
Set pin speed to fast mode.
static void pin_speed_high (const uint32_t pin)
Set pin speed to highest mode.
Detailed Description
Pin speed manipulation.
Function Documentation
static void pin_speed_fast (const uint32_t pin) static
Set pin speed to fast mode.
As an side effect, maximum current draw from/to the pin will be less limited.
Warning
Should be called after output mode set. Do not call when pin is in input or analog mode.
Parameters
[in] pin pin name (pin_name_base)
Definition at line 156 of file pin_v0.h.
References _pin_pinno(), _pin_port(), and _pin_setspd().
static void pin_speed_high (const uint32_t pin) static
Set pin speed to highest mode.
As an side effect, maximum current draw from/to the pin will not be limited, allowing external device may destroy the pin during collision.
Warning
Should be called after output mode set. Do not call when pin is in input or analog mode.
Note
when architecture doesn't support this mode, the meaning should be same as pin_speed_fast function
Parameters
[in] pin pin name (pin_name_base)
Definition at line 161 of file pin_v0.h.
References _pin_pinno(), _pin_port(), and _pin_setspd().
static void pin_speed_low (const uint32_t pin) static
Set pin speed to slowest mode.
As an side effect, maximum current draw from/to the pin will be very limited.
Warning
Should be called after output mode set. Do not call when pin is in input or analog mode.
Parameters
[in] pin pin name (pin_name_base)
Definition at line 146 of file pin_v0.h.
References _pin_pinno(), _pin_port(), and _pin_setspd().
static void pin_speed_medium (const uint32_t pin) static
Set pin speed to medium speed mode.
As an side effect, maximum current draw from/to the pin will be limited.
Warning
Should be called after output mode set. Do not call when pin is in input or analog mode.
Parameters
[in] pin pin name (pin_name_base)
Definition at line 151 of file pin_v0.h.
References _pin_pinno(), _pin_port(), and _pin_setspd().